sudo: required
language: node_js
node_js:
  - "8.2.1"
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
  
services:
  - docker
  
cache:
  directories:
  - node_modules

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - tar -xvzf ./database/avatax.tar.gz
  - npm install -g newman nyc

jobs:
  include:
    - stage: Install dependencies
      script: 
        - npm install

    - stage: Build project
      script:
        - npm build

    - stage: Run unit tests
      script:
        - echo "Run unit tests"

    - stage: Up image docker
      script:
        - docker-compose up -d

    - stage: Restore mongo data
      script:
        - docker exec -it pocexpressgraphql_db_1 mongorestore -d avatax /data/db/backup

    - stage: Test API
        - npm run test-api

notifications:
  email:
    on_success: never
    on_failure: always