sudo: required
language: node_js
node_js:
  - "8.2.1"
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
  
services:
  - docker
  
cache:
  directories:
  - node_modules

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
before_script:
  - mkdir backup
  - chmod +x ./backup
  - tar -cvzf ./database/avatax.tar.gz ./backup
  - npm install -g newman
  - docker-compose up -d

script:
  - newman run tests/agasts.check.response.json -e test.postman_environment.json

after_success:
  - docker-compose down

notifications:
  email:
    on_success: never
    on_failure: always