sudo: required
language: node_js
node_js:
  - "8.2.1"
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
  
services:
  - docker
  
cache:
  directories:
  - node_modules

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

stages:
  - Run unit tests
  - Run integrated tests
  - name: Release to DEV
    # require the branch name to be master
    if: branch = master
  - name: Release to HOMOLOG
    # require the branch name to be pre-production
    if: branch = pre-production
  - name: Release to PRD
    # require the branch name to be production
    if: branch = production

jobs:
  include:
    - stage: Run unit tests
      script:
        - npm install
        - npm build
        - echo "Run unit tests"

    - stage: Run integrated tests
      before_script:
        - tar -xvzf ./database/avatax.tar.gz
        - npm install -g newman nyc
      script:
        - docker-compose up -d
        - docker exec -it pocexpressgraphql_db_1 mongorestore -d avatax /data/db/backup
        - npm run test-api
    
    - stage: Release to DEV
      script:
        - echo "Release to DEV"

    - stage: Release to HOMOLOG
      script:
        - echo "Release to HOMOLOG"

    - stage: Release to PRD
      script:
        - echo "Release to PRD"

notifications:
  email:
    on_success: never
    on_failure: always