db:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - ./backup:/data/db
  command: "--smallfiles --logpath=/dev/null"
api:
  build: .
  command: npm start
  volumes:
    - .:/data
  ports:
    - "5000:5000"
  links:
    - db