db:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - .:/data/db
  command: "--smallfiles --logpath=/dev/null"
api:
  build: .
  command: npm run coverage
  volumes:
    - .:/.
  ports:
    - "5000:5000"
  links:
    - db